### ISSUE TITLE
Selectable background color

### ISSUE THREAD

**Issue by A380Coding** [hotNipi/node-red-dashboard-2-ui-gauge-linear#4]
Background color is the same color as defined for the linear gauge but dimmed by some value.
Can we have selectable background color. E.g. Grey color for the background

**Comment by A380Coding** [comment]
Just beautification.
If there area many gauges it looks quite colorful

**Comment by A380Coding** [comment]
For comparison:
https://raw.githubusercontent.com/hotNipi/node-red-contrib-ui-level/master/img/node-red-dashboard-ui-level.JPG

**Comment by hotNipi** [comment]
Yeah, that. 
Current solution is way different. Adding a background color means to add one additional div element per cell. It's very bad idea because of element count should be kept as low as possible. This node is already violating that rule. 
If to make color fade to gray (and that gray can be anything but gray) - the intermediate states will be pretty ugly colorwise. 

So still, I am not convinced.

**Comment by A380Coding** [comment]
Understand, I was not looking from a technical view. I was only looking at the optical result.

**Comment by hotNipi** [comment]
Closed with constructive arguments agreed.
